---
name: HA Remote Logger
description: A custom API to add logs to HA
version: 1.0.2
slug: rss_log_feed
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
options:
  log_ttl: 259200
  sftp_hostname: homeassistant.local
  sftp_username: root
  sftp_b64_pkey_string: <Paste your key here>
schema:
  log_ttl: int
  sftp_hostname: str
  sftp_username: str
  sftp_b64_pkey_string: str
ports:
  8001/tcp: 8001
