---
version: '3'

services:
  run:
    build:
      args:
        - BUILD_FROM=homeassistant/amd64-base:latest
    env_file:
      - .env
    environment:
      - LOG_TTL=259200
    ports:
      - 8001:8001
